-- Superseded migration.
-- The final provider-neutral payment/check-out design is implemented in:
--   20261004_updates.sql
-- Keep this file as a marker so a migration runner does not apply the old
-- Razorpay-only order/RLS model a second time.
